//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoe_api.Models
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:shoe_api/Models/buy_materials_details.cs
    public partial class buy_materials_details
    {
        public int buy_materials_details_id { get; set; }
        public string materialrs_order_id { get; set; }
        public int materialr_details_num { get; set; }
        public int materialr_details_id { get; set; }
    
        public virtual materials_order materials_order { get; set; }
        public virtual materialr materialr { get; set; }
=======
    public partial class in_repertory_detail_Result
    {
        public int quality_testing_id { get; set; }
        public System.DateTime quality_testing_time { get; set; }
        public string result { get; set; }
        public string product_name { get; set; }
        public string operator_per { get; set; }
        public int pro_production_id { get; set; }
>>>>>>> 4e67ba7110b18aca8319f40becc9c670632008b3:shoe_api/Models/in_repertory_detail_Result.cs
    }
}
