//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoe_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials_plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materials_plan()
        {
            this.materials_order = new HashSet<materials_order>();
            this.materials_plan_details = new HashSet<materials_plan_details>();
        }
    
        public int materialr_plan_id { get; set; }
        public string status { get; set; }
        public string operator_per { get; set; }
        public string person_handling { get; set; }
        public System.DateTime materials_plan_time { get; set; }
        public string operator_per { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materials_order> materials_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materials_plan_details> materials_plan_details { get; set; }
    }
}
