//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoe_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materialr()
        {
            this.buy_materials_details = new HashSet<buy_materials_details>();
            this.materialr_details = new HashSet<materialr_details>();
            this.materialr_epertory = new HashSet<materialr_epertory>();
            this.materials_plan_details = new HashSet<materials_plan_details>();
            this.out_materialr = new HashSet<out_materialr>();
        }
    
        public int materialr_details_id { get; set; }
        public string materialr_details_name { get; set; }
        public int materialr_type_id { get; set; }
        public decimal materialr_details_price { get; set; }
        public string material_supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buy_materials_details> buy_materials_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialr_details> materialr_details { get; set; }
        public virtual materialr_type materialr_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materialr_epertory> materialr_epertory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materials_plan_details> materials_plan_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<out_materialr> out_materialr { get; set; }
    }
}
