//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoe_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoeEntities : DbContext
    {
        public ShoeEntities()
            : base("name=ShoeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<buy_materials_details> buy_materials_details { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<get_materials> get_materials { get; set; }
        public virtual DbSet<in_materialr> in_materialr { get; set; }
        public virtual DbSet<in_money> in_money { get; set; }
        public virtual DbSet<in_repertory> in_repertory { get; set; }
        public virtual DbSet<materialr> materialr { get; set; }
        public virtual DbSet<materialr_details> materialr_details { get; set; }
        public virtual DbSet<materialr_epertory> materialr_epertory { get; set; }
        public virtual DbSet<materialr_type> materialr_type { get; set; }
        public virtual DbSet<materials_order> materials_order { get; set; }
        public virtual DbSet<materials_plan> materials_plan { get; set; }
        public virtual DbSet<materials_plan_details> materials_plan_details { get; set; }
        public virtual DbSet<materials_quality_testing> materials_quality_testing { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<out_materialr> out_materialr { get; set; }
        public virtual DbSet<out_money> out_money { get; set; }
        public virtual DbSet<out_repertory> out_repertory { get; set; }
        public virtual DbSet<pro_production> pro_production { get; set; }
        public virtual DbSet<pro_repertory> pro_repertory { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_plan> product_plan { get; set; }
        public virtual DbSet<product_plan_details> product_plan_details { get; set; }
        public virtual DbSet<product_quality_testing> product_quality_testing { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<proPlan_ordDetails> proPlan_ordDetails { get; set; }
    
        public virtual ObjectResult<add_pro_repertory_Result> add_pro_repertory(Nullable<int> pro_product_id)
        {
            var pro_product_idParameter = pro_product_id.HasValue ?
                new ObjectParameter("pro_product_id", pro_product_id) :
                new ObjectParameter("pro_product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<add_pro_repertory_Result>("add_pro_repertory", pro_product_idParameter);
        }
    
        public virtual ObjectResult<customer_order_details_Result> customer_order_details(string customer_orderid)
        {
            var customer_orderidParameter = customer_orderid != null ?
                new ObjectParameter("customer_orderid", customer_orderid) :
                new ObjectParameter("customer_orderid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<customer_order_details_Result>("customer_order_details", customer_orderidParameter);
        }
    
        public virtual ObjectResult<daijianchanpinbianxie_Result> daijianchanpinbianxie(Nullable<int> pro_production_id)
        {
            var pro_production_idParameter = pro_production_id.HasValue ?
                new ObjectParameter("pro_production_id", pro_production_id) :
                new ObjectParameter("pro_production_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<daijianchanpinbianxie_Result>("daijianchanpinbianxie", pro_production_idParameter);
        }
    
        public virtual ObjectResult<in_repertory_detail_Result> in_repertory_detail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<in_repertory_detail_Result>("in_repertory_detail");
        }
    
        public virtual ObjectResult<materialr_details_materialr_Result> materialr_details_materialr(Nullable<int> material_id)
        {
            var material_idParameter = material_id.HasValue ?
                new ObjectParameter("material_id", material_id) :
                new ObjectParameter("material_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<materialr_details_materialr_Result>("materialr_details_materialr", material_idParameter);
        }
    
        public virtual ObjectResult<pro_plan_details_Result> pro_plan_details(Nullable<int> pro_plan_id)
        {
            var pro_plan_idParameter = pro_plan_id.HasValue ?
                new ObjectParameter("pro_plan_id", pro_plan_id) :
                new ObjectParameter("pro_plan_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_plan_details_Result>("pro_plan_details", pro_plan_idParameter);
        }
    
        public virtual ObjectResult<select_customer_details_Result> select_customer_details(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_customer_details_Result>("select_customer_details", order_idParameter);
        }
    
        public virtual ObjectResult<select_in_money_Result> select_in_money()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_in_money_Result>("select_in_money");
        }
    
        public virtual ObjectResult<select_materialrs_details_Result> select_materialrs_details(string materialrs_order_id)
        {
            var materialrs_order_idParameter = materialrs_order_id != null ?
                new ObjectParameter("materialrs_order_id", materialrs_order_id) :
                new ObjectParameter("materialrs_order_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_materialrs_details_Result>("select_materialrs_details", materialrs_order_idParameter);
        }
    
        public virtual ObjectResult<select_materials_order_plan_mpd_Result> select_materials_order_plan_mpd(Nullable<int> materials_order_id)
        {
            var materials_order_idParameter = materials_order_id.HasValue ?
                new ObjectParameter("materials_order_id", materials_order_id) :
                new ObjectParameter("materials_order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_materials_order_plan_mpd_Result>("select_materials_order_plan_mpd", materials_order_idParameter);
        }
    
        public virtual ObjectResult<select_order_details_cust_pro_Result> select_order_details_cust_pro(string ord)
        {
            var ordParameter = ord != null ?
                new ObjectParameter("ord", ord) :
                new ObjectParameter("ord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_order_details_cust_pro_Result>("select_order_details_cust_pro", ordParameter);
        }
    
        public virtual ObjectResult<select_out_money_Result> select_out_money()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_out_money_Result>("select_out_money");
        }
    
        public virtual ObjectResult<select_out_repertory_Result> select_out_repertory(Nullable<int> out_repertory_id)
        {
            var out_repertory_idParameter = out_repertory_id.HasValue ?
                new ObjectParameter("out_repertory_id", out_repertory_id) :
                new ObjectParameter("out_repertory_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_out_repertory_Result>("select_out_repertory", out_repertory_idParameter);
        }
    
        public virtual ObjectResult<select_Pro_order_datails_Result> select_Pro_order_datails(string pro_order)
        {
            var pro_orderParameter = pro_order != null ?
                new ObjectParameter("Pro_order", pro_order) :
                new ObjectParameter("Pro_order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_Pro_order_datails_Result>("select_Pro_order_datails", pro_orderParameter);
        }
    
        public virtual ObjectResult<select_pro_plan_details_Result> select_pro_plan_details(Nullable<int> pro_plan_details)
        {
            var pro_plan_detailsParameter = pro_plan_details.HasValue ?
                new ObjectParameter("pro_plan_details", pro_plan_details) :
                new ObjectParameter("pro_plan_details", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_pro_plan_details_Result>("select_pro_plan_details", pro_plan_detailsParameter);
        }
    
        public virtual ObjectResult<select_product_pro_plan_Result> select_product_pro_plan(Nullable<int> pro_production_id)
        {
            var pro_production_idParameter = pro_production_id.HasValue ?
                new ObjectParameter("pro_production_id", pro_production_id) :
                new ObjectParameter("pro_production_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_product_pro_plan_Result>("select_product_pro_plan", pro_production_idParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<xp_SelectPageCaigou_Result> xp_SelectPageCaigou(Nullable<int> pageIndex, Nullable<int> pageSize, string pageWhere)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageWhereParameter = pageWhere != null ?
                new ObjectParameter("PageWhere", pageWhere) :
                new ObjectParameter("PageWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageCaigou_Result>("xp_SelectPageCaigou", pageIndexParameter, pageSizeParameter, pageWhereParameter);
        }
    
        public virtual ObjectResult<xp_SelectPageCaigou_Detail_Result> xp_SelectPageCaigou_Detail(Nullable<int> pageIndex, Nullable<int> pageSize, string id)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageCaigou_Detail_Result>("xp_SelectPageCaigou_Detail", pageIndexParameter, pageSizeParameter, idParameter);
        }
    
        public virtual ObjectResult<xp_SelectPageCaiLiao_Result> xp_SelectPageCaiLiao(Nullable<int> pageIndex, Nullable<int> pageSize, string pageWhere)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageWhereParameter = pageWhere != null ?
                new ObjectParameter("PageWhere", pageWhere) :
                new ObjectParameter("PageWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageCaiLiao_Result>("xp_SelectPageCaiLiao", pageIndexParameter, pageSizeParameter, pageWhereParameter);
        }
    
        public virtual ObjectResult<xp_SelectPageChuku_Result> xp_SelectPageChuku(Nullable<int> pageIndex, Nullable<int> pageSize, string pageWhere)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageWhereParameter = pageWhere != null ?
                new ObjectParameter("PageWhere", pageWhere) :
                new ObjectParameter("PageWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageChuku_Result>("xp_SelectPageChuku", pageIndexParameter, pageSizeParameter, pageWhereParameter);
        }
    
        public virtual ObjectResult<xp_SelectPageJihua_Result> xp_SelectPageJihua(Nullable<int> pageIndex, Nullable<int> pageSize, string pageWhere)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageWhereParameter = pageWhere != null ?
                new ObjectParameter("PageWhere", pageWhere) :
                new ObjectParameter("PageWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageJihua_Result>("xp_SelectPageJihua", pageIndexParameter, pageSizeParameter, pageWhereParameter);
        }
    
        public virtual ObjectResult<xp_SelectPageJihua_detail_Result> xp_SelectPageJihua_detail(Nullable<int> pageIndex, Nullable<int> pageSize, string id)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageJihua_detail_Result>("xp_SelectPageJihua_detail", pageIndexParameter, pageSizeParameter, idParameter);
        }
    
        public virtual ObjectResult<xp_SelectPageRuku_Result> xp_SelectPageRuku(Nullable<int> pageIndex, Nullable<int> pageSize, string pageWhere)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var pageWhereParameter = pageWhere != null ?
                new ObjectParameter("PageWhere", pageWhere) :
                new ObjectParameter("PageWhere", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xp_SelectPageRuku_Result>("xp_SelectPageRuku", pageIndexParameter, pageSizeParameter, pageWhereParameter);
        }
    }
}
