//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoe_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_repertory
    {
        public int repertory_id { get; set; }
        public int pro_repertory_num { get; set; }
        public int product_id { get; set; }
        public virtual product product { get; set; }
    }
}
